<?php

namespace Database\Seeders;

use App\Models\Individuals;
use Illuminate\Database\Seeder;

class IndividualsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Individuals::create([
            'CCI2024No' => '14493021',
            'DateCreated' => '2021-11-17T03:19:56.186Z',
            'LastName' => 'Dela Cruz',
            'MiddleName' => 'Corazon',
            'FirstName' => 'Juan',
            'ExtensionName' => '',
            'Sex' => 'Male',
            'Region' => '1',
            'Province' => 'La Union',
            'Municipality' => 'San Juan',
            'DateOfBirth' => '2002-09-04',
            'PlaceOfBirth' => 'La Union',
            'CivilStatus' => 'Single',
            'Citizenship' => 'Filipino',
            'ICRNo' => '',
            'Height' => 175,
            'Weight' => 58,
            'Employed' => 'Yes',
            'profession' => 'Teacher',
            'TIN' => '123456789',
            'GrossEarnings' => 224000.00,
            'validId' => 'ID12345',
            'taxableAmount' => 100000.00,
            'basicCommunityTax' => 500.00,
            'communityTaxDue' => 250,
            'Total' => 1250.00,
            'Interest' => 13.44,
            'TotalAmountPaid' => 1263.44,
            'paymentMethod' => 'Cash',
            'paymentReferenceNumber' => 'PRN12345',
            'ticketNumber' => 1
        ]);

        // Add 4 more dummy entries here
        Individuals::create([
            'CCI2024No' => '14493022',
            'DateCreated' => '2021-11-18T04:20:57.187Z',
            'LastName' => 'Garcia',
            'MiddleName' => 'Santos',
            'FirstName' => 'Maria',
            'ExtensionName' => '',
            'Sex' => 'Female',
            'Region' => '1',
            'Province' => 'La Union',
            'Municipality' => 'San Fernando',
            'DateOfBirth' => '1995-07-21',
            'PlaceOfBirth' => 'La Union',
            'CivilStatus' => 'Married',
            'Citizenship' => 'Filipino',
            'ICRNo' => '',
            'Height' => 165,
            'Weight' => 55,
            'Employed' => 'No',
            'profession' => 'Engineer',
            'TIN' => '987654321',
            'GrossEarnings' => 300000.00,
            'validId' => 'ID12346',
            'taxableAmount' => 150000.00,
            'basicCommunityTax' => 600.00,
            'communityTaxDue' => 300,
            'Total' => 1500.00,
            'Interest' => 15.50,
            'TotalAmountPaid' => 1515.50,
            'paymentMethod' => 'Credit Card',
            'paymentReferenceNumber' => 'PRN12346',
            'ticketNumber' => 2
        ]);

        Individuals::create([
            'CCI2024No' => '14493023',
            'DateCreated' => '2021-11-19T05:21:58.188Z',
            'LastName' => 'Reyes',
            'MiddleName' => 'Martinez',
            'FirstName' => 'Carlos',
            'ExtensionName' => '',
            'Sex' => 'Male',
            'Region' => '1',
            'Province' => 'La Union',
            'Municipality' => 'Agoo',
            'DateOfBirth' => '1988-12-15',
            'PlaceOfBirth' => 'La Union',
            'CivilStatus' => 'Married',
            'Citizenship' => 'Filipino',
            'ICRNo' => '',
            'Height' => 166,
            'Weight' => 70,
            'Employed' => 'Yes',
            'profession' => 'Doctor',
            'TIN' => '112233445',
            'GrossEarnings' => 500000.00,
            'validId' => 'ID12347',
            'taxableAmount' => 200000.00,
            'basicCommunityTax' => 700.00,
            'communityTaxDue' => 400,
            'Total' => 1800.00,
            'Interest' => 20.00,
            'TotalAmountPaid' => 1820.00,
            'paymentMethod' => 'Bank Transfer',
            'paymentReferenceNumber' => 'PRN12347',
            'ticketNumber' => 3
        ]);

        Individuals::create([
            'CCI2024No' => '14493024',
            'DateCreated' => '2021-11-20T06:22:59.189Z',
            'LastName' => 'Santos',
            'MiddleName' => 'Lorenzo',
            'FirstName' => 'Ana',
            'ExtensionName' => '',
            'Sex' => 'Female',
            'Region' => '1',
            'Province' => 'La Union',
            'Municipality' => 'Bauang',
            'DateOfBirth' => '1975-03-30',
            'PlaceOfBirth' => 'La Union',
            'CivilStatus' => 'Single',
            'Citizenship' => 'Filipino',
            'ICRNo' => '',
            'Height' => 155,
            'Weight' => 60,
            'Employed' => 'No',
            'profession' => 'Businesswoman',
            'TIN' => '223344556',
            'GrossEarnings' => 150000.00,
            'validId' => 'ID12348',
            'taxableAmount' => 75000.00,
            'basicCommunityTax' => 500.00,
            'communityTaxDue' => 250,
            'Total' => 1000.00,
            'Interest' => 10.00,
            'TotalAmountPaid' => 1010.00,
            'paymentMethod' => 'Cash',
            'paymentReferenceNumber' => 'PRN12348',
            'ticketNumber' => 4
        ]);

        Individuals::create([
            'CCI2024No' => '14493025',
            'DateCreated' => '2021-11-21T07:23:48.190Z',
            'LastName' => 'Aquino',
            'MiddleName' => 'Cruz',
            'FirstName' => 'Pedro',
            'ExtensionName' => '',
            'Sex' => 'Male',
            'Region' => '1',
            'Province' => 'La Union',
            'Municipality' => 'Aringay',
            'DateOfBirth' => '1990-01-05',
            'PlaceOfBirth' => 'La Union',
            'CivilStatus' => 'Single',
            'Citizenship' => 'Filipino',
            'ICRNo' => '',
            'Height' => 161,
            'Weight' => 65,
            'Employed' => 'Yes',
            'profession' => 'Lawyer',
            'TIN' => '334455667',
            'GrossEarnings' => 400000.00,
            'validId' => 'ID12349',
            'taxableAmount' => 180000.00,
            'basicCommunityTax' => 600.00,
            'communityTaxDue' => 300,
            'Total' => 1500.00,
            'Interest' => 15.00,
            'TotalAmountPaid' => 1515.00,
            'paymentMethod' => 'Credit Card',
            'paymentReferenceNumber' => 'PRN12349',
            'ticketNumber' => 5
        ]);
    }
}
